name: "coverage"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'project-b/**'
      - '!project-b/README.md'
      # - '!project-b/<any-other-file-you-want-to-exclude>'
jobs:
  coverage:
    env:
      HUSKY: 0 # Disable Husky to avoid pre-commit hooks
    permissions:
      contents: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: "project-b"
